server:
  port: 80

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: url-shortener-service
              uri: ${URL_SHORTENER_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/shorten
                - Method=POST

            - id: url-shortener-service-delete
              uri: ${URL_SHORTENER_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/{shortCode}
                - Method=DELETE

            - id: url-redirect-service
              uri: ${URL_REDIRECT_SERVICE_URL:http://localhost:8086}
              predicates:
                - Path=/{shortCode}
                - Method=GET

            - id: analytics-service
              uri: ${ANALYTICS_SERVICE_URL:http://localhost:8087}
              predicates:
                - Path=/analytics/**
                - Method=GET

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG