server:
  port: 8087

spring:
  application:
    name: analytics-service

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/urlshortener}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres123}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate        # never modify schema ? read only service
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

clickhouse:
  url: ${CLICKHOUSE_URL:http://localhost:8123}
  database: ${CLICKHOUSE_DATABASE:analytics}
  username: ${CLICKHOUSE_USER:default}
  password: ${CLICKHOUSE_PASSWORD:clickhouse123}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.urlshortener: INFO