server:
  port: 8086

spring:
  application:
    name: url-redirect-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis123}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  jackson:
    serialization:
      write-dates-as-timestamps: false

rate-limit:
  redirect-rpm: 300

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.urlshortener: INFO