server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /shorten {
        proxy_pass         http://api-gateway:80;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_pass_request_headers on;
    }

    location /analytics {
        proxy_pass         http://api-gateway:80;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_pass_request_headers on;
    }

    location ~ ^/[a-zA-Z0-9]\{7\}$ {
        proxy_pass         http://api-gateway:80;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_pass_request_headers on;
        proxy_method       $request_method;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}